version: '3'

services:

  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    command: gunicorn --bind=0.0.0.0:5000 wsgi:app
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - db

  worker:
    build: .
    command: python manage.py run_worker
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - db

  redis:
    image: redis:6.2-alpine

  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data: